[package]
name = "is31fl3730"
version = "0.0.1"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.2"
heapless = "0.4.2"
bitcanvas = { path = "../bitcanvas" }